#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Mar 24, 2022 12:45:57 AM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import TESTGUI_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+468+138")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#ffffff")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.317, rely=0.022, height=51, width=94)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d86c69")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''HIRING HACK''')

        self.Labelframe1 = tk.LabelFrame(self.top)
        self.Labelframe1.place(relx=0.017, rely=0.133, relheight=0.767
                , relwidth=1.017)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Labelframe''')
        self.Labelframe1.configure(background="#ffffff")

        self.Labelframe2 = tk.LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.049, rely=0.058, relheight=0.913
                , relwidth=0.756, bordermode='ignore')
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Labelframe''')
        self.Labelframe2.configure(background="#ffffff")
        self.Labelframe2.configure(highlightcolor="#ffffff")

        self.Label2 = tk.Label(self.Labelframe2)
        self.Label2.place(relx=0.065, rely=0.032, height=49, width=64
                , bordermode='ignore')
        self.Label2.configure(activebackground="#000000")
        self.Label2.configure(activeforeground="white")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''NAME''')

        self.Entry1 = tk.Entry(self.Labelframe2)
        self.Entry1.place(relx=0.499, rely=0.063, height=20, relwidth=0.204
                , bordermode='ignore')
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label3 = tk.Label(self.Labelframe2)
        self.Label3.place(relx=0.065, rely=0.159, height=49, width=54
                , bordermode='ignore')
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''AGE''')

        self.Entry2 = tk.Entry(self.Labelframe2)
        self.Entry2.place(relx=0.499, rely=0.19, height=20, relwidth=0.182
                , bordermode='ignore')
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Label4 = tk.Label(self.Labelframe2)
        self.Label4.place(relx=0.065, rely=0.317, height=31, width=64
                , bordermode='ignore')
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''SEX''')

        self.Entry3 = tk.Entry(self.Labelframe2)
        self.Entry3.place(relx=0.499, rely=0.317, height=20, relwidth=0.182
                , bordermode='ignore')
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")

        self.Label5 = tk.Label(self.Labelframe2)
        self.Label5.place(relx=0.065, rely=0.444, height=31, width=194
                , bordermode='ignore')
        self.Label5.configure(activeforeground="#ffffff")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''DO YOU ENJOY NEW EXPERIENCES''')

        self.Entry4 = tk.Entry(self.Labelframe2)
        self.Entry4.place(relx=0.499, rely=0.444, height=20, relwidth=0.182
                , bordermode='ignore')
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Label6 = tk.Label(self.Labelframe2)
        self.Label6.place(relx=0.065, rely=0.571, height=21, width=184
                , bordermode='ignore')
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#ffffff")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''DO YOU FEEL NEGATIVITY''')

        self.Entry5 = tk.Entry(self.Labelframe2)
        self.Entry5.place(relx=0.499, rely=0.571, height=20, relwidth=0.182
                , bordermode='ignore')
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")

        self.Label7 = tk.Label(self.Labelframe2)
        self.Label7.place(relx=0.065, rely=0.667, height=21, width=194
                , bordermode='ignore')
        self.Label7.configure(activeforeground="#ffffff")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#ffffff")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''ARE YOU A TEAM PLAYER''')

        self.Entry6 = tk.Entry(self.Labelframe2)
        self.Entry6.place(relx=0.499, rely=0.667, height=20, relwidth=0.182
                , bordermode='ignore')
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")

        self.Label8 = tk.Label(self.Labelframe2)
        self.Label8.place(relx=0.065, rely=0.762, height=21, width=194
                , bordermode='ignore')
        self.Label8.configure(anchor='w')
        self.Label8.configure(background="#ffffff")
        self.Label8.configure(compound='left')
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''ARE YOU AN EXTROVERT''')

        self.Entry7 = tk.Entry(self.Labelframe2)
        self.Entry7.place(relx=0.499, rely=0.762, height=20, relwidth=0.182
                , bordermode='ignore')
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(insertbackground="black")

        self.Button1 = tk.Button(self.Labelframe2)
        self.Button1.place(relx=0.738, rely=0.889, height=24, width=107
                , bordermode='ignore')
        self.Button1.configure(activebackground="#ffffff")
        self.Button1.configure(activeforeground="#ffffff")
        self.Button1.configure(background="#b90746")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''SUBMIT''')

def start_up():
    TESTGUI_support.main()

if __name__ == '__main__':
    TESTGUI_support.main()




